# Generated by Django 5.2.10 on 2026-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_profile_profile_pic_post_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
